title: "Kagan Bağdemir"
description: "Technische Zeichnung, CAD-Unterstützung, Datenanalyse und Logistik-KPI-Dashboards aus Dortmund"
url: "https://kaganbagdemir.de"
baseurl: ""
permalink: /blog/:title/
markdown: kramdown

# SEO için
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Sosyal/künye
author:
  name: "Kagan Bağdemir"
social:
  links:
    - "https://github.com/kahnri"
    - "https://www.linkedin.com/in/kagan-b-7b2b28206/"
    - "mailto:kb2011kb2011@gmail.com"
